#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo "------- 🔍 Checking frontend lint and types -------"
cd frontend
npm run check:all


echo "------- 🔍 Checking backend lint and types -------"
cd ../backend
npm run check:all


echo "✅ All checks passed, you can proceed with the commit!"