#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

echo "------- 🔍 Checking frontend lint and types -------"
cd frontend2 && npx lint-staged


echo "------- 🔍 Checking backend lint and types -------"
cd ../backend && npx lint-staged


echo "✅ All checks passed, you can proceed with the commit!"